git restore --staged 23_AdvancedInteractions/PlaywrightElementsAdvanced/CalculateExampleLambda.cs
git restore --staged 23_AdvancedInteractions/PlaywrightElementsAdvanced/DotNetTestExamples.txt
git restore --staged 23_AdvancedInteractions/PlaywrightElementsAdvanced/package-lock.json
git restore --staged 23_AdvancedInteractions/PlaywrightElementsAdvanced/package.json
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/AddRemoveElements.cs
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/Checkboxes.cs
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/ElementInteractionsMSTest.csproj
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/HoverOverItems.cs
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/JavaScriptAlert.cs
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/KeyPresses.cs
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/SecureAreaLogin.cs
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/SelectDropDownItem.cs
git restore --staged 23_AdvancedInteractions/TestDropDownOptions/TestBase.cs
